### ISSUE TITLE
Question about max_step

### ISSUE THREAD

**Issue by manishemirani** [aryana-haghjoo/SummerSchool#1]
Hi,

In the mcmc function, you defined a variable called max_step. My question is, does the process of initializing the arrays(e.g chain and chisq) considered the first step?

Otherwise, I think the max_step in the "for loop" should replace with the max_step + 1.

**Comment by aryana-haghjoo** [comment]
Hi,
The first step is considered as the 0th element of the 2D array. Thus, when defining the range for the for loop, we start it from 1 rather 0.
That's why we do not need to put nstep +1.

Regards,
Aryana

On Aug. 21, 2022 9:58 a.m., manishemirani ***@***.***> wrote:

Hi,

In the mcmc function, you defined a variable called max_step. My question is, does the process of initializing the arrays(e.g chain and chisq) considered the first step?

Otherwise, I think the max_step in the "for loop" should replace with the max_step + 1.

**Comment by manishemirani** [comment]
Thanks, Ms. Haghjoo,

I think to preserve other issues about the number of steps, it's better to
add a comment for the mcmc function.

Sincerely,
Mani Shemiranifar
